// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Author documents
 */
interface AuthorDocumentData {
  /**
   * Author Name field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.author_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_name: prismic.KeyTextField;

  /**
   * Author Role field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.author_role
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_role: prismic.KeyTextField;

  /**
   * Author Image field in *Author*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: author.author_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  author_image: prismic.ImageField<never>;
}

/**
 * Author document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AuthorDocumentData>, "author", Lang>;

type BlogArticleDocumentDataSlicesSlice = never;

/**
 * Content for Blog Article documents
 */
interface BlogArticleDocumentData {
  /**
   * Title field in *Blog Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Author field in *Blog Article*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<"author">;

  /**
   * Excerpt field in *Blog Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  excerpt: prismic.RichTextField;

  /**
   * Featured Image field in *Blog Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Category field in *Blog Article*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<"blog_category">;

  /**
   * Slice Zone field in *Blog Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogArticleDocumentDataSlicesSlice> /**
   * Meta Description field in *Blog Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Blog Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Blog Article document from Prismic
 *
 * - **API ID**: `blog_article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogArticleDocumentData>,
    "blog_article",
    Lang
  >;

/**
 * Content for Blog Category documents
 */
interface BlogCategoryDocumentData {
  /**
   * Category Name field in *Blog Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_category.category_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category_name: prismic.KeyTextField;
}

/**
 * Blog Category document from Prismic
 *
 * - **API ID**: `blog_category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogCategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogCategoryDocumentData>,
    "blog_category",
    Lang
  >;

type BlogIndexDocumentDataSlicesSlice = never;

/**
 * Content for Blog Index documents
 */
interface BlogIndexDocumentData {
  /**
   * Title field in *Blog Index*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_index.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Blog Index*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_index.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Slice Zone field in *Blog Index*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_index.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogIndexDocumentDataSlicesSlice> /**
   * Meta Description field in *Blog Index*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_index.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_index.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Blog Index*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_index.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Blog Index document from Prismic
 *
 * - **API ID**: `blog_index`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogIndexDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BlogIndexDocumentData>,
    "blog_index",
    Lang
  >;

/**
 * Item in *Footer → Links*
 */
export interface FooterDocumentDataLinksItem {
  /**
   * Link field in *Footer → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *Footer → Links*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;
}

/**
 * Item in *Footer → Social Links*
 */
export interface FooterDocumentDataSocialLinksItem {
  /**
   * Icon field in *Footer → Social Links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_links[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Link field in *Footer → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<FooterDocumentDataLinksItem>>;

  /**
   * Social Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_links: prismic.GroupField<Simplify<FooterDocumentDataSocialLinksItem>>;

  /**
   * Copyright field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copyright: prismic.RichTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomePageDocumentDataSlicesSlice = HomepageSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

/**
 * Item in *HomepageDocumentation → DocumentationEfficiency*
 */
export interface HomepagedocumentationDocumentDataDocumentationefficiencyItem {
  /**
   * Documentation_EfficiencyPtag field in *HomepageDocumentation → DocumentationEfficiency*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentationefficiency[].documentation_efficiencyptag
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  documentation_efficiencyptag: prismic.RichTextField;

  /**
   * DocumentationH3tag field in *HomepageDocumentation → DocumentationEfficiency*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentationefficiency[].documentationh3tag
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  documentationh3tag: prismic.RichTextField;

  /**
   * Documentation_Ptag field in *HomepageDocumentation → DocumentationEfficiency*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentationefficiency[].documentation_ptag
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  documentation_ptag: prismic.RichTextField;
}

/**
 * Item in *HomepageDocumentation → Documentation_AI_Content*
 */
export interface HomepagedocumentationDocumentDataDocumentationAiContentItem {
  /**
   * Documentation_AI_para1 field in *HomepageDocumentation → Documentation_AI_Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentation_ai_content[].documentation_ai_para1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  documentation_ai_para1: prismic.RichTextField;

  /**
   * Documentation_AI_H3tag field in *HomepageDocumentation → Documentation_AI_Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentation_ai_content[].documentation_ai_h3tag
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  documentation_ai_h3tag: prismic.RichTextField;

  /**
   * Documentation_AI_para2 field in *HomepageDocumentation → Documentation_AI_Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentation_ai_content[].documentation_ai_para2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  documentation_ai_para2: prismic.RichTextField;
}

/**
 * Item in *HomepageDocumentation → Documentation_Optimizing_Content*
 */
export interface HomepagedocumentationDocumentDataDocumentationOptimizingContentItem {
  /**
   * Documentation_Optimizing_Para1 field in *HomepageDocumentation → Documentation_Optimizing_Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentation_optimizing_content[].documentation_optimizing_para1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  documentation_optimizing_para1: prismic.RichTextField;

  /**
   * Documentation_Optimizing_H3Tag field in *HomepageDocumentation → Documentation_Optimizing_Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentation_optimizing_content[].documentation_optimizing_h3tag
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  documentation_optimizing_h3tag: prismic.RichTextField;

  /**
   * Documentation_Optimizing_Para2 field in *HomepageDocumentation → Documentation_Optimizing_Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentation_optimizing_content[].documentation_optimizing_para2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  documentation_optimizing_para2: prismic.RichTextField;
}

/**
 * Item in *HomepageDocumentation → Documentation_Testimonial*
 */
export interface HomepagedocumentationDocumentDataDocumentationTestimonialItem {
  /**
   * Documentation_TestimonialBgImage field in *HomepageDocumentation → Documentation_Testimonial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentation_testimonial[].documentation_testimonialbgimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  documentation_testimonialbgimage: prismic.ImageField<never>;

  /**
   * Documentation_TestimonialImage field in *HomepageDocumentation → Documentation_Testimonial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentation_testimonial[].documentation_testimonialimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  documentation_testimonialimage: prismic.ImageField<never>;

  /**
   * Documentation_TestimonialPara1 field in *HomepageDocumentation → Documentation_Testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentation_testimonial[].documentation_testimonialpara1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  documentation_testimonialpara1: prismic.RichTextField;

  /**
   * Documentation_TestimonialPara2 field in *HomepageDocumentation → Documentation_Testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentation_testimonial[].documentation_testimonialpara2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  documentation_testimonialpara2: prismic.RichTextField;

  /**
   * Documentation_TestimonialPara3 field in *HomepageDocumentation → Documentation_Testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentation_testimonial[].documentation_testimonialpara3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  documentation_testimonialpara3: prismic.RichTextField;
}

/**
 * Content for HomepageDocumentation documents
 */
interface HomepagedocumentationDocumentData {
  /**
   * DocumentationH2 field in *HomepageDocumentation*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentationh2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  documentationh2: prismic.RichTextField;

  /**
   * DocumentationEfficiency field in *HomepageDocumentation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentationefficiency[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  documentationefficiency: prismic.GroupField<
    Simplify<HomepagedocumentationDocumentDataDocumentationefficiencyItem>
  >;

  /**
   * Documentation_ParallelMobileImg1 field in *HomepageDocumentation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentation_parallelmobileimg1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  documentation_parallelmobileimg1: prismic.ImageField<never>;

  /**
   * Documentation_Vector1 field in *HomepageDocumentation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentation_vector1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  documentation_vector1: prismic.ImageField<never>;

  /**
   * Documentation_AI_image field in *HomepageDocumentation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentation_ai_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  documentation_ai_image: prismic.ImageField<never>;

  /**
   * Documentation_AI_Content field in *HomepageDocumentation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentation_ai_content[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  documentation_ai_content: prismic.GroupField<
    Simplify<HomepagedocumentationDocumentDataDocumentationAiContentItem>
  >;

  /**
   * Documentation_AI_Vector2 field in *HomepageDocumentation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentation_ai_vector2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  documentation_ai_vector2: prismic.ImageField<never>;

  /**
   * Documentation_Optimizing_Content field in *HomepageDocumentation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentation_optimizing_content[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  documentation_optimizing_content: prismic.GroupField<
    Simplify<HomepagedocumentationDocumentDataDocumentationOptimizingContentItem>
  >;

  /**
   * Documentation_ParallelMobileImg2 field in *HomepageDocumentation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentation_parallelmobileimg2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  documentation_parallelmobileimg2: prismic.ImageField<never>;

  /**
   * Documentation_Testimonial field in *HomepageDocumentation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentation_testimonial[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  documentation_testimonial: prismic.GroupField<
    Simplify<HomepagedocumentationDocumentDataDocumentationTestimonialItem>
  >;

  /**
   * Documentation_Testimonial_SmallIcon field in *HomepageDocumentation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepagedocumentation.documentation_testimonial_smallicon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  documentation_testimonial_smallicon: prismic.ImageField<never>;
}

/**
 * HomepageDocumentation document from Prismic
 *
 * - **API ID**: `homepagedocumentation`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepagedocumentationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepagedocumentationDocumentData>,
    "homepagedocumentation",
    Lang
  >;

/**
 * Item in *HomepageLanding → FeatureBoxes*
 */
export interface LandingDocumentDataFeatureboxesItem {
  /**
   * count1 field in *HomepageLanding → FeatureBoxes*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.featureboxes[].count1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  count1: prismic.ImageField<never>;

  /**
   * FeatureIcon1 field in *HomepageLanding → FeatureBoxes*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.featureboxes[].featureicon1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featureicon1: prismic.ImageField<never>;

  /**
   * FeatureHeading3 field in *HomepageLanding → FeatureBoxes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.featureboxes[].featureheading3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  featureheading3: prismic.RichTextField;

  /**
   * FeatureParagraph field in *HomepageLanding → FeatureBoxes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.featureboxes[].featureparagraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  featureparagraph: prismic.RichTextField;
}

/**
 * Content for HomepageLanding documents
 */
interface LandingDocumentData {
  /**
   * Feature_Heading2 field in *HomepageLanding*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.feature_heading2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_heading2: prismic.RichTextField;

  /**
   * FeatureBoxes field in *HomepageLanding*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.featureboxes[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  featureboxes: prismic.GroupField<
    Simplify<LandingDocumentDataFeatureboxesItem>
  >;

  /**
   * GetStartedBGImage field in *HomepageLanding*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.getstartedbgimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  getstartedbgimage: prismic.ImageField<never>;

  /**
   * GetStartedh2 field in *HomepageLanding*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.getstartedh2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  getstartedh2: prismic.RichTextField;

  /**
   * GetStartedParagraph field in *HomepageLanding*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.getstartedparagraph
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  getstartedparagraph: prismic.RichTextField;

  /**
   * GetStartedLinkBtn field in *HomepageLanding*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.getstartedlinkbtn
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  getstartedlinkbtn: prismic.LinkField;

  /**
   * GetStartedBtnLabel field in *HomepageLanding*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.getstartedbtnlabel
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  getstartedbtnlabel: prismic.KeyTextField;
}

/**
 * HomepageLanding document from Prismic
 *
 * - **API ID**: `landing`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingDocumentData>,
    "landing",
    Lang
  >;

type LandingPageDocumentDataSlicesSlice = never;

/**
 * Content for Landing Page documents
 */
interface LandingPageDocumentData {
  /**
   * Slice Zone field in *Landing Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LandingPageDocumentDataSlicesSlice> /**
   * Meta Description field in *Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landing_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Landing Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landing_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Canonical Link field in *Landing Page*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.canonical_link
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  canonical_link: prismic.LinkField;
}

/**
 * Landing Page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingPageDocumentData>,
    "landing_page",
    Lang
  >;

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Optional - Label for the link
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.TitleField;

  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the site
   * - **API ID Path**: settings.siteTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  siteTitle: prismic.TitleField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | AuthorDocument
  | BlogArticleDocument
  | BlogCategoryDocument
  | BlogIndexDocument
  | FooterDocument
  | HomePageDocument
  | HomepagedocumentationDocument
  | LandingDocument
  | LandingPageDocument
  | NavigationDocument
  | SettingsDocument;

/**
 * Primary content in *Homepage → Primary*
 */
export interface HomepageSliceDefaultPrimary {
  /**
   * Banner_heading field in *Homepage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.primary.banner_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  banner_heading: prismic.RichTextField;

  /**
   * Banner_paragraph field in *Homepage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.primary.banner_paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  banner_paragraph: prismic.RichTextField;

  /**
   * Banner_Image field in *Homepage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.primary.banner_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner_image: prismic.ImageField<never>;
}

/**
 * Default variation for Homepage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomepageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomepageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Homepage*
 */
type HomepageSliceVariation = HomepageSliceDefault;

/**
 * Homepage Shared Slice
 *
 * - **API ID**: `homepage`
 * - **Description**: Homepage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomepageSlice = prismic.SharedSlice<
  "homepage",
  HomepageSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AuthorDocument,
      AuthorDocumentData,
      BlogArticleDocument,
      BlogArticleDocumentData,
      BlogArticleDocumentDataSlicesSlice,
      BlogCategoryDocument,
      BlogCategoryDocumentData,
      BlogIndexDocument,
      BlogIndexDocumentData,
      BlogIndexDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataLinksItem,
      FooterDocumentDataSocialLinksItem,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      HomepagedocumentationDocument,
      HomepagedocumentationDocumentData,
      HomepagedocumentationDocumentDataDocumentationefficiencyItem,
      HomepagedocumentationDocumentDataDocumentationAiContentItem,
      HomepagedocumentationDocumentDataDocumentationOptimizingContentItem,
      HomepagedocumentationDocumentDataDocumentationTestimonialItem,
      LandingDocument,
      LandingDocumentData,
      LandingDocumentDataFeatureboxesItem,
      LandingPageDocument,
      LandingPageDocumentData,
      LandingPageDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      HomepageSlice,
      HomepageSliceDefaultPrimary,
      HomepageSliceVariation,
      HomepageSliceDefault,
    };
  }
}
