// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  aboutus: dynamic(() => import("./Aboutus")),
  faqs_page: dynamic(() => import("./FaqsPage")),
  homepage: dynamic(() => import("./Homepage")),
};
