// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  aboutus: dynamic(() => import("./Aboutus")),
  faqs_page: dynamic(() => import("./FaqsPage")),
  hero: dynamic(() => import("./Hero")),
  homepage: dynamic(() => import("./Homepage")),
  rich_text: dynamic(() => import("./RichText")),
};
